name: FirstPlugin
version: '1.0'
main: example.firstplugin.FirstPlugin  # Vollständiger Pfad zur Hauptklasse
api-version: '1.20'
commands:
  rtp:
    description: Teleportiert dich zufällig
    usage: /rtp

  stp:
    description: Teleportiert dich gewünscht auf den Boden
    usage: /stp

  runturtle:
    description: Lässt Schildkröten schneller laufen, wenn du Angst hast
    usage: /runturtle

  pspsps:
    description: Katzen lieben dich
    usage: /pspsps